events { worker_connections 1024; }

http {
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log warn;

  server {
    listen 80;

    location / {
      proxy_pass http://backend:8080/;
    }
  }
}
